plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - ".git/**/*"
    - "docs/**/*"
    - "script/**/*"


Layout/CaseIndentation: { Enabled: false }
Layout/SpaceBeforeBlockBraces: { Enabled: false }
Lint/AssignmentInCondition: { Enabled: false }
Lint/UnusedBlockArgument: { Enabled: false }
Lint/UnusedMethodArgument: { Enabled: false }
Metrics/BlockLength: { Enabled: false }
Naming/BlockForwarding: { Enabled: false }
Performance/RedundantBlockCall: { Enabled: false }
RSpec/DescribedClass: { Enabled: false }
RSpec/SpecFilePathFormat: { Enabled: false }
Style/ArgumentsForwarding: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/FormatString: { Enabled: false }
Style/FormatStringToken: { Enabled: false }
Style/MethodDefParentheses: { Enabled: false }
Style/NumericPredicate: { Enabled: false }
Style/RedundantStructKeywordInit: { Enabled: false }
Style/SingleArgumentDig: { Enabled: false }

Layout/EndAlignment: { EnforcedStyleAlignWith: start_of_line }
Layout/LineLength: { Max: 200 } # def 120
Layout/SpaceInsideBlockBraces: { SpaceBeforeBlockParameters: false }
Naming/MemoizedInstanceVariableName: { EnforcedStyleForLeadingUnderscores: required }
Naming/MethodParameterName: { MinNameLength: 2 } # def 3
Naming/PredicateMethod: { AllowedMethods: ["call", "format"], AllowedPatterns: [\Aappinfo_] }
Naming/RescuedExceptionsVariableName: { PreferredName: ex }
RSpec/ExampleLength: { Max: 20 } # def 5
RSpec/MultipleExpectations: { Max: 10 } # def 1
RSpec/NestedGroups: { Max: 4 } # def 3
RSpec/NotToNot: { EnforcedStyle: to_not }
Style/Alias: { EnforcedStyle: prefer_alias_method }
Style/PercentLiteralDelimiters: { PreferredDelimiters: { "default": "{}", "%i": "[]", "%I": "[]", "%r": "{}", "%w": "[]", "%W": "[]"} }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: comma }

Metrics/AbcSize: { Max: 51 } # def 17 / t 68
Metrics/ClassLength: { Max: 200 } # def 100
Metrics/CyclomaticComplexity: { Max: 14 } # def 7 / t 21
Metrics/MethodLength: { Max: 64 } # def 10 / t 64
Metrics/ModuleLength: { Max: 200 } # def 100
Metrics/ParameterLists: { Max: 8 } # def 5
Metrics/PerceivedComplexity: { Max: 16 } # def 8 / t 24
