#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "irb"
require "iparty"
require "iparty/cli/application"

app = IParty::CLI::Application.new(argv: ARGV, argf: ARGF, env: ENV)
app.dispatch
